apiVersion: v2
name: lightrag-server
version: 0.0.5
appVersion: 1.3.8
dependencies:
  - name: redis
    version: 20.1.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: cluster
    version: 0.0.11
    repository: https://cloudnative-pg.github.io/charts
    alias: cnpg
    condition: cnpg.enabled
  - name: neo4j
    version: '0.4.8'
    repository: https://charts.bitnami.com/bitnami
    condition: neo4j.enabled
