{{ $chartName := "argo-cd" }}
{{ $repoURL := "https://argoproj.github.io/argo-helm" }}
{{ $appConfig := merge (index $.Values $chartName) $.Values.common }}
{{- if ne $appConfig.enabled false }}
{{ $argoConfig := merge (default $appConfig.argocdApps (dict)) $.Values.argocdApps }}
{{ $appName := default $chartName $appConfig.nameOverride }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appName }}
  namespace: {{ $argoConfig.namespace }}
  annotations: {{ toYaml $argoConfig.annotations | nindent 4 }}
spec:
  project: {{ $argoConfig.project }}
  destination:
    namespace: {{ default $appName $appConfig.namespace }}
    server: {{ $argoConfig.destination.server }}
  syncPolicy: {{ toYaml $argoConfig.syncPolicy | nindent 4 }}
  source: 
    repoURL: {{ $repoURL }}
    chart: {{ $chartName }}
    targetRevision: {{ $appConfig.targetRevision }}
    helm:
      valuesObject:
{{- if $appConfig.helmConfig }}
{{ toYaml $appConfig.helmConfig | indent 8 }}
{{- else }}
        {{- if (not (not $appConfig.ingress.rootDomain)) }}
        global:
          domain: "argocd.{{ $appConfig.ingress.rootDomain }}"
        {{- end }}
        configs:
          params:
            server.insecure: true
          {{- if $appConfig.config.repositories }}
          repositories: {{ toYaml $appConfig.config.repositories | nindent 12 }}
          {{- end }}
          {{- if $appConfig.config.credentialTemplates }}
          credentialTemplates: {{ toYaml $appConfig.config.credentialTemplates | nindent 12 }}
          {{- end }}
          cm:
            exec.enabled: {{ $appConfig.config.execEnabled }}
            {{- if eq $appConfig.auth.type "google" }}
            dex.config: |
              connectors:
              - config:
                  issuer: https://accounts.google.com
                  clientID: {{ $appConfig.auth.oauthClientID }}
                  clientSecret: {{ $appConfig.auth.oauthClientSecret }}
                type: oidc
                id: google
                name: Google
            {{- end }}
            resource.customizations.health.argoproj.io_Application: |
              hs = {}
              hs.status = "Progressing"
              hs.message = ""
              if obj.status ~= nil then
                if obj.status.health ~= nil then
                  hs.status = obj.status.health.status
                  if obj.status.health.message ~= nil then
                    hs.message = obj.status.health.message
                  end
                end
              end
              return hs
          {{- if $appConfig.config.rbac }}
          rbac: {{ toYaml $appConfig.config.rbac | nindent 12 }}
          {{- end }}
        redis-ha:
          enabled: true
          replicas: {{ max 2 $appConfig.redundancy.replicas }}
        controller: { replicas: {{ $appConfig.redundancy.replicas }} }
        applicationSet: { replicas: {{ $appConfig.redundancy.replicas }} }
        repoServer:
          autoscaling:
            enabled: true
            minReplicas: 2
          {{- if $appConfig.config.repoServer.volumes }}
          volumes: {{ toYaml $appConfig.config.repoServer.volumes | nindent 12 }}
          {{- end }}
          {{- if $appConfig.config.repoServer.volumeMounts }}
          volumeMounts: {{ toYaml $appConfig.config.repoServer.volumeMounts | nindent 12 }}
          {{- end }}
          {{- if $appConfig.config.repoServer.env }}
          env: {{ toYaml $appConfig.config.repoServer.env | nindent 12 }}
          {{- end }}
          {{- if $appConfig.config.repoServer.initContainers }}
          initContainers: {{ toYaml $appConfig.config.repoServer.initContainers | nindent 12 }}
          {{- end }}
        server:
          autoscaling:
            enabled: true
            minReplicas: 2
          ingress:
            enabled: {{ and (default false $appConfig.ingress.enabled) (not (not $appConfig.ingress.rootDomain)) }}
            {{- if and (default false $appConfig.ingress.enabled) (not (not $appConfig.ingress.rootDomain)) }}
            https: true
            ingressClassName: {{ $appConfig.ingress.ingressClassName }}
            annotations:
              cert-manager.io/cluster-issuer: {{ $appConfig.ingress.clusterIssuer }}
            hosts:
              - "argocd.{{ $appConfig.ingress.rootDomain }}"
            tls:
              - secretName: {{ $appName }}-tls
                hosts:
                  - "argocd.{{ $appConfig.ingress.rootDomain }}"
            {{- end }}
{{- end }}
{{- end }}
