{{- range $className, $configData := .Values.storageClasses }}
{{- if ne $configData.enabled false }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ printf "%s" $className }}
provisioner: io.openebs.csi-mayastor
reclaimPolicy: {{ default "Delete" $configData.reclaimPolicy }}
volumeBindingMode: {{ default "WaitForFirstConsumer" $configData.volumeBindingMode }}
parameters:
  fsType: {{ default "ext4" $configData.fsType | quote }}
  thin: {{ (default false $configData.thin) | quote }}
  allowVolumeExpansion: {{ (default true $configData.allowVolumeExpansion) | quote }}
  protocol: {{ default "nvmf" $configData.protocol | quote }}
  repl: {{ (default "3" $configData.repl) | quote }}
{{- end }}
{{- end }}
