{
 "title": "Vespa Detailed Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(vespa_container_status,namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(vespa_container_status{namespace=~\"$namespace\",job=~\"$job\",container=~\"$container\",pod=~\"$pod\"},job)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(vespa_container_status{namespace=~\"$namespace\", job=~\"$job\"},container)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(vespa_container_status{namespace=~\"$namespace\", job=~\"$job\", container=~\"$container\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Content Node Documents",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "content_proton_documentdb_documents_total_last{namespace=~\"$namespace\",job=~\"$job\",container=~\"$container\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "queries_rate{namespace=~\"$namespace\",job=~\"$job\",container=~\"$container\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Feed Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "feed_operations_rate{namespace=~\"$namespace\",job=~\"$job\",container=~\"$container\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "95p (AVG)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "query_latency_95percentile{namespace=~\"$namespace\",job=~\"$job\",container=~\"$container\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "99p (AVG)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "query_latency_99percentile{namespace=~\"$namespace\",job=~\"$job\",container=~\"$container\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "mean",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "query_latency_average{namespace=~\"$namespace\",job=~\"$job\",container=~\"$container\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Http Status 200 Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_status_2xx_rate{namespace=~\"$namespace\",job=~\"$job\",container=~\"$container\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Http Status 4xx Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_status_4xx_rate{namespace=~\"$namespace\",job=~\"$job\",container=~\"$container\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "container http 5xx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "http_status_5xx_rate{namespace=~\"$namespace\",job=~\"$job\",container=~\"$container\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "cpu{namespace=~\"$namespace\",job=~\"$job\",container=~\"$container\",pod=~\"$pod\"}"
    }
   ]
  },
  {
   "title": "Proton Document Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "content_proton_documentdb_disk_usage_last{namespace=~\"$namespace\",job=~\"$job\",container=~\"$container\",pod=~\"$pod\"} / (1024 * 1024)"
    }
   ]
  },
  {
   "title": "Proton Resource Disk Usage Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "content_proton_resource_usage_disk_average{namespace=~\"$namespace\",job=~\"$job\",container=~\"$container\",pod=~\"$pod\"} * 100"
    }
   ]
  },
  {
   "title": "Proton Memory Usage Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "content_proton_resource_usage_memory_average{namespace=~\"$namespace\",job=~\"$job\",container=~\"$container\",pod=~\"$pod\"} * 100"
    }
   ]
  }
 ]
}