{
 "title": "Vespa Basic Monitoring Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(vespa_container_status,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Performance Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Feed Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "feed_operations_rate", "legendFormat": "Feed Operations / Second" }
   ]
  },
  {
   "title": "Query Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "queries_rate", "legendFormat": "Queries / Second" }
   ]
  },
  {
   "title": "Total Documents",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "content_proton_documentdb_documents_total_last",
     "legendFormat": "Total Documents in Storage"
    }
   ]
  },
  {
   "title": "Query: Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "query_latency_average", "legendFormat": "Average Query Latency" }
   ]
  },
  {
   "title": "Query: 95 Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "query_latency_95percentile", "legendFormat": "95 Percentile Query Latency" }
   ]
  },
  {
   "title": "Query: 99 Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "query_latency_99percentile", "legendFormat": "99 Percentile Query Latency" }
   ]
  }
 ]
}