{{ $chartName := "onyx" }}
{{ $helmRepo := "https://zadarastorage.github.io/helm-charts" }}
{{ $gitRepo := "https://github.com/zadarastorage/helm-charts.git" }}
{{ $chartPath := "charts/onyx" }}
{{ $appConfig := merge (index $.Values $chartName) $.Values.common }}
{{- if ne $appConfig.enabled false }}
{{ $argoConfig := merge (default $appConfig.argocdApps (dict)) $.Values.argocdApps }}
{{ $appName := default $chartName $appConfig.nameOverride }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appName }}
  namespace: {{ $argoConfig.namespace }}
  annotations: {{ toYaml $argoConfig.annotations | nindent 4 }}
spec:
  project: {{ $argoConfig.project }}
  destination:
    namespace: {{ default $appName $appConfig.namespace }}
    server: {{ $argoConfig.destination.server }}
  syncPolicy: {{ toYaml $argoConfig.syncPolicy | nindent 4 }}
  source:
{{- if eq $appConfig.chartSource "helm" }}
    repoURL: {{ $helmRepo }}
    chart: {{ $chartName }}
{{- else if eq $appConfig.chartSource "git" }}
    repoURL: {{ $gitRepo }}
    path: {{ $chartPath }}
{{- end }}
    targetRevision: {{ $appConfig.targetRevision }}
    helm:
      valuesObject:
{{- if $appConfig.helmConfig }}
{{ toYaml $appConfig.helmConfig | indent 8 }}
{{- else }}
        cnpg:
          cluster:
            instances: 3
            monitoring:
              enabled: {{ (default false $appConfig.monitoring.enabled) }}
          pooler:
            instances: 3
            monitoring:
              enabled: {{ (default false $appConfig.monitoring.enabled) }}
        {{- range $i, $section := (list "inference" "index") }}
        {{ $section }}:
          runtimeClassName: nvidia
          resources:
            requests:
              nvidia.com/gpu: 4
            limits:
              nvidia.com/gpu: 4
          tolerations:
            - key: nvidia.com/gpu
              operator: Exists
              effect: NoSchedule
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - key: nvidia.com/device-plugin.config
                    operator: In
                    values:
                      - tesla-25b6
                      - tesla-2235
                      - tesla-27b8
                      - tesla-26b9
        {{- end }}
        ingress:
          enabled: {{ and (default false $appConfig.ingress.enabled) (not (not $appConfig.ingress.rootDomain)) }}
          {{- if and (default false $appConfig.ingress.enabled) (not (not $appConfig.ingress.rootDomain)) }}
          annotations:
            cert-manager.io/cluster-issuer: self-signed
          hostname: "onyx.{{ $appConfig.ingress.rootDomain }}"
          tls: true
          {{- end }}
{{- end }}
{{- end }}
