{{ $chartName := "onyx" }}
{{ $helmRepo := "https://zadarastorage.github.io/helm-charts" }}
{{ $gitRepo := "https://github.com/zadarastorage/helm-charts.git" }}
{{ $chartPath := "charts/onyx" }}
{{ $appConfig := merge (index $.Values $chartName) $.Values.common }}
{{- if ne $appConfig.enabled false }}
{{ $argoConfig := merge (default $appConfig.argocdApps (dict)) $.Values.argocdApps }}
{{ $appName := default $chartName $appConfig.nameOverride }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $appName }}
  namespace: {{ $argoConfig.namespace }}
  annotations: {{ toYaml $argoConfig.annotations | nindent 4 }}
spec:
  project: {{ $argoConfig.project }}
  destination:
    namespace: {{ default $appName $appConfig.namespace }}
    server: {{ $argoConfig.destination.server }}
  syncPolicy: {{ toYaml $argoConfig.syncPolicy | nindent 4 }}
  source:
{{- if eq $appConfig.chartSource "helm" }}
    repoURL: {{ $helmRepo }}
    chart: {{ $chartName }}
{{- else if eq $appConfig.chartSource "git" }}
    repoURL: {{ $gitRepo }}
    path: {{ $chartPath }}
{{- end }}
    targetRevision: {{ $appConfig.targetRevision }}
    helm:
      valuesObject:
{{- if $appConfig.helmConfig }}
{{ toYaml $appConfig.helmConfig | indent 8 }}
{{- else }}
        cnpg:
          cluster:
            instances: {{ $appConfig.redundancy.replicas }}
            monitoring:
              enabled: {{ (default false $appConfig.monitoring.enabled) }}
          pooler:
            instances: {{ $appConfig.redundancy.replicas }}
            monitoring:
              enabled: {{ (default false $appConfig.monitoring.enabled) }}
        vespa:
          statefulSets:
            single: { enabled: false }
            cfg:
              enabled: true
              replicaCount: {{ $appConfig.redundancy.replicas }}
            content:
              enabled: true
              replicaCount: {{ $appConfig.redundancy.replicas }}
        configMap:
          vespa:
            VESPA_CONFIG_SERVER_HOST: 'vespa-cfg'
            VESPA_HOST: 'vespa-content'
          {{- if default false $appConfig.config.configMap.web }}
          web: {{ toYaml $appConfig.config.configMap.web | nindent 12 }}
          {{- end }}
          {{- if or (default false $appConfig.config.configMap.auth) (ne appConfig.auth.type "none") }}
          auth:
            {{- if eq appConfig.auth.type "google" }}
            AUTH_TYPE: google_oauth
            GOOGLE_OAUTH_CLIENT_ID: {{ $appConfig.auth.oauthClientID }}
            GOOGLE_OAUTH_CLIENT_SECRET: {{ $appConfig.auth.oauthClientSecret }}
            {{- if $appConfig.auth.oauthValidEmailDomains }}
            VALID_EMAIL_DOMAINS: {{ $appConfig.auth.oauthValidEmailDomains }}
            {{- end }}
            {{- else if eq appConfig.auth.type "basic" }}
            AUTH_TYPE: basic
            {{- end }}
            {{- if default false $appConfig.config.configMap.auth }}
            {{ toYaml $appConfig.config.configMap.auth | nindent 12 }}
            {{- end }}
          {{- end }}
        hotpatch:
          vespaRedundancy: {{ (div $appConfig.redundancy.replicas 2) | add1 }}
        web:
          replicaCount: {{ $appConfig.redundancy.replicas }}
        api:
          replicaCount: 1
        worker:
          replicaCount: 1
        {{- range $i, $section := (list "inference" "index") }}
        {{ $section }}:
          replicaCount: 1
          runtimeClassName: nvidia
          tolerations:
            - key: nvidia.com/gpu
              operator: Exists
              effect: NoSchedule
          resources: {{ toYaml $appConfig.config.inference.resources | nindent 12 }}
          affinity: {{ toYaml $appConfig.config.inference.affinity | nindent 12 }}
          # TODO Revise ^ to do a map lookup for configure these seperately
        {{- end }}
        ingress:
          enabled: {{ default false $appConfig.ingress.enabled }}
          {{- if default false $appConfig.ingress.enabled }}
          annotations:
            cert-manager.io/cluster-issuer: {{ $appConfig.ingress.clusterIssuer }}
          tls: true
          {{- if not (not $appConfig.ingress.rootDomain) }}
          hostname: "onyx.{{ $appConfig.ingress.rootDomain }}"
          {{- end }}
          {{- end }}
        redis:
          master:
            revisionHistoryLimit: {{ $appConfig.revisionHistoryLimit }}
{{- end }}
{{- end }}
