# -- ArgoCD Application defaults for all applications
argocdApps:
  # -- Set default ArgoCD Project to designate
  project: default
  # -- Set default namespace to put the ArgoCD App CRD into
  namespace: argocd
  # -- Set default argocd destination configuration
  destination:
    server: https://kubernetes.default.svc
  # -- Set default syncPolicy for all apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      #- ServerSideApply=true
  # -- Set default annotations for the application
  annotations:
    argocd.argoproj.io/sync-wave: "20"

# -- Set common settings to be used in all applications
common:
  # -- Common defaults applied to ingresses in all applications
  ingress:
    # -- Enable ingresses for all applications
    enabled: true
    # -- Set root domain to use for ingress rules of all applications
    rootDomain: ''
    # -- Set default ingressClassName
    ingressClassName: traefik
    # -- Set default cert-manager cluster-issuer
    clusterIssuer: selfsigned
  monitoring:
    # -- Enable pod/service monitors
    enabled: false
    # -- Override monitor label
    label: victoria-metrics-k8s-stack
  # -- Set default redundancy configurations
  redundancy:
    replicas: 3
  # -- Default revisionHistoryLimit where applicable
  revisionHistoryLimit: 2
  auth:
    # -- Set auth type if application supports it [none|basic|google]
    type: none
    # -- OAuth client ID for google
    oauthClientID:
    # -- OAuth client secret for google
    oauthClientSecret:
    oauthValidEmailDomains: []

ollama:
  # -- Enable ollama
  enabled: true
  # -- Set chart version/revision
  targetRevision: 1.12.0
  argocdApps:
    annotations:
      argocd.argoproj.io/sync-wave: "11"
  config:
    # -- Set list of models to be preloaded into ollama
    models:
      - llama3.1:8b-instruct-q8_0
  resources:
    requests:
      cpu: 4
      memory: 15Gi
      nvidia.com/gpu: 8
    limits:
      cpu: 8
      memory: 20Gi
      nvidia.com/gpu: 8
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
            - key: nvidia.com/device-plugin.config
              operator: In
              values:
                - tesla-25b6
                - tesla-2235
                - tesla-27b8
                - tesla-26b9

onyx:
  # -- Enable onyx
  enabled: true
  # -- Set chart source. git/helm
  chartSource: helm
  # -- Set chart version/revision
  targetRevision: 0.0.13
  config:
    configMap:
      # -- Configmap for setting Onyx Env Vars to all pods
      global: {}
      # -- Configmap for setting Onyx Env Vars for authentication
      auth: {}
      # -- Configmap for setting Onyx Env Vars related to web
      web: {}
    inference:
      resources:
        requests:
          nvidia.com/gpu: 4
        limits:
          nvidia.com/gpu: 4
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: nvidia.com/device-plugin.config
                  operator: In
                  values:
                    - tesla-25b6
                    - tesla-2235
                    - tesla-27b8
                    - tesla-26b9
    index:
      resources:
        requests:
          nvidia.com/gpu: 4
        limits:
          nvidia.com/gpu: 4
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: nvidia.com/device-plugin.config
                  operator: In
                  values:
                    - tesla-25b6
                    - tesla-2235
                    - tesla-27b8
                    - tesla-26b9
