{{- if and (.Values.podDisruptionBudget).enabled (not .Values.knative.enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "llama-cpp-server.fullname" . }}
  labels:
    {{- include "llama-cpp-server.labels" . | nindent 4 }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "llama-cpp-server.selectorLabels" . | nindent 6 }}
{{- end }}
